# 这个工作流作用：
# 1. 在提交 `main` 分支时
# 2. 同步 gitee
name: Sync Gitee

on: [push, delete]

jobs:
  mirror_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - name: check_gitee_token
        run: |
          if [ -z "${{ secrets.GITEE_USER_NAME }}" ] || [ -z "${{ secrets.GITEE_RSA_PRIVATE_KEY }}" ]; then
          echo "Error: GITEE_USER_NAME or GITEE_RSA_PRIVATE_KEY is not set."
            echo see https://github.com/pixta-dev/repository-mirroring-action for help.
            echo 打开 https://zhuanlan.zhihu.com/p/353862378 , 查看 "Gitee 和 Github 添加公钥" "3.Github仓库添加私钥"
            echo 打开 https://gitee.com/profile/sshkeys ， 添加GITEE公钥
            echo 打开 https://github.com/<YOUR_USERNAME>/ipxefm/settings/secrets/actions ， 添加 GITEE_USER_NAME 和 GITEE_RSA_PRIVATE_KEY
            exit 1
          fi


      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Mirror to gitee"
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@gitee.com:${{secrets.GITEE_USER_NAME}}/ipxefm.git
          ssh_private_key: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
